### ISSUE TITLE
Maintain feature IDs during metric computation

### ISSUE THREAD

**Issue by philipperufin** [michellepicoli/segmetric#88]
Hello,
Thanks for the nice package! I´m using sm_read() and sm_compute() to calculate the IoU between reference data and predictions. Doing that I obtain IoU scores for a subset of the reference polygons (assuming some don´t overlap with a prediction, etc.). I am interested in stratifying the IoU scores across different attributes contained in the original sf polygons, but am not sure if (and how) I would be able to merge/join the IoU scores with the sf objects used to compute them. 
Could you help me out here? 
Thanks in advance!

**Comment by albhasan** [comment]
So, you'd like to get the metrics values back as a new column in one of your original SF object, wouldn't you?

I don't think segmetric can handle your use case because the metrics have different scopes, that is, different metrics are computed on different combinations of segmentation and reference data. (See [Costa et al. 2018](10.1016/j.rse.2017.11.024)) and it would be confusing (or even meaningless) to link metric values with specific instances of either reference or segmentation polygons.

What you could do is, for example, split your reference and segmentation data into the strata you need and then calling segmetric for each stratum (combination of segmentation and reference data) and use the results to assemble (by hand) a new data.frame.  Even after this, I would be careful while making inferences about subsets of data using different metrics because of their different scope and semantics.

**Comment by philipperufin** [comment]
Thanks for the prompt reply! I understand that the idea in itself would not make sense for all metrics implemented in segmetric. To my understanding however, IoU scores could be assessed at the object-level, right? In that sense, producing a graph like Fig 8c in [Wang et al. 2022](https://doi.org/10.3390/rs14225738) should be straight forward if scores could be linked with the original data. If you don´t see any option for facilitating this in segmetric, I could of course go ahead and calculate IoU scores for each pair of reference and prediction individually, it just seems to be a tideous effort. Again thanks for your time!

**Comment by rolfsimoes** [comment]
This can done using the snippet below.
The `sm_metric_subset()` function retrieves the combination between reference and segments along the metric values. The trick to combine this object with your original data is to use `ref_id` and `seg_id` columns as the row number of input reference and segment data, respectively. 

``` r
library(segmetric)
#> Loading required package: sf
#> Linking to GEOS 3.10.2, GDAL 3.4.3, PROJ 8.2.0; sf_use_s2() is TRUE

# load example datasets
data("sample_ref_sf", package = "segmetric")
data("sample_seg_sf", package = "segmetric")

# create segmetric object
m <- sm_read(ref_sf = sample_ref_sf, seg_sf = sample_seg_sf)
m <- sm_compute(m, metric_id = "IoU")

# get the subset universe of IoU metric
s <- sm_metric_subset(m, metric_id = "IoU")

# list the subset for each metric
names(s)
#> [1] "IoU"

# ref_id and seg_id are the row numbers of the input 
# reference and segment sf polygons
s$IoU$ref_id
#> [1] 1 2 3 4 5
s$IoU$seg_id
#> [1] 5 4 6 2 1

# get the original segment id for each corresponding row
s$IoU$id <- sample_seg_sf[s$IoU$seg_id, ]$id

# this is what you need ##############################
s$IoU
#> Simple feature collection with 5 features and 4 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -46.18962 ymin: -12.25326 xmax: -46.15782 ymax: -12.21884
#> Geodetic CRS:  WGS 84
#>     ref_id seg_id                       geometry       IoU  id
#> 1.1      1      5 POLYGON ((-46.16572 -12.228... 0.9207850 200
#> 2        2      4 POLYGON ((-46.1712 -12.2324... 0.8488788 173
#> 3        3      6 POLYGON ((-46.17008 -12.219... 0.9368885 229
#> 4        4      2 POLYGON ((-46.17726 -12.226... 0.8483754 119
#> 5        5      1 POLYGON ((-46.18949 -12.253... 0.5872686  85
```

<sup>Created on 2023-04-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Please, note the returned geometries are the intersection between reference and segmentation data. 
The `id` column refers to the original segmentation id. You can use it to join with your data.

**Comment by philipperufin** [comment]
Great - thank you!
